# Generated by Django 6.1 on 2026-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='predicted_class',
            field=models.TextField(blank=True, default=''),
        ),
    ]
